float64[100] hip_lpin_torque
float64[100] hip_rpin_torque
float64[100] left_knee_pin_torque
float64[100] right_knee_pin_torque
float64[100] hip_lpin_state
float64[100] hip_rpin_state
float64[100] left_knee_pin_state
float64[100] right_knee_pin_state
---
string result
