float64[100] planar_x
float64[100] planar_z
float64[100] hip_lpin
float64[100] hip_rpin
float64[100] left_knee_pin
float64[100] right_knee_pin
float64[100] left_ankle
float64[100] right_ankle

float64[100] planar_xdot
float64[100] planar_zdot
float64[100] hip_lpindot
float64[100] hip_rpindot
float64[100] left_knee_pindot
float64[100] right_knee_pindot
float64[100] left_ankledot
float64[100] right_ankledot

